---
# tasks file for OSP6-backup
# file: roles/OSP6-backup/tasks/main.yml

- name: Install rsync
  yum:
    name: rsync
    state: present
  tags:
    - rsync
    - install

- name: Install MySQL-python
  yum:
    name: MySQL-python
    state: present
  tags:
    - mysql
    - install

- name: Create mysqldump of all databases
  mysql_db:
    state: dump
    name: all
    target: "/{{ BACKUP_LOCATION }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}.sql"
  tags:
    - mysql
    - database

- name: Backup etc configurations
  synchronize:
    archive: yes
    src: "/etc/{{ items }}"
    dest: "/{{ BACKUP_LOCATION }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-{{ items }}-etc"
  with_items:
    - glance
    - swift
    - nova
  tags:
    - etc
    - rsync

- name: Backup /var/lib configurations except the instances directory
  synchronize:
    archive: yes
    src: "/var/lib/{{ items }}"
    dest: "/{{ BACKUP_LOCATION }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-{{ items }}-varlib"
    rsync_opts:
      - "--no-motd"
      - "--exclude 'instances'"
  with_items:
    - glance
    - swift
    - nova
  tags:
    - varlib
    - rsync

- name: Backup /var/log files
  synchronize:
    archive: yes
    src: "/var/log/{{ items }}"
    dest: "/{{ BACKUP_LOCATION }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-{{ items }}-varlog"
  with_items:
    - glance
    - swift
    - nova
  tags:
    - varlog
    - rsync

- name: Backup /var/lib/glance/images files
  synchronize:
    archive: yes
    src: /var/lib/glance/images
    dest: "/{{ BACKUP_LOCATION }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-glance-varlibglanceimages"
  tags:
    - glance
    - rsync
